FROM node:12


WORKDIR /home/node/app


RUN mkdir -p /home/node/app
# RUN mkdir -p /home/node/app/application
RUN chmod -R 777 /home/node/app
USER node
# RUN chmod -R 777 /home/node/app/application
# COPY ./app/application ./

# RUN chmod -R 777 /home/node/app
# RUN chmod -R 777 /home/node/app
# chmod -R 777 /var/project
# RUN chown node:node /home/node/app

# EXPOSE 3000